---
# Install specified version of node.js into the system

# Add nodesource to RPM. Unfortunately, the URL is version dependent. When we
# upgrade node.js, we will have to upgrade this URL as well.
- name: add node.js rpm to yum
  shell: 'curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -'

- name: install nodejs
  yum:
    name: "nodejs-{{ nodejs_version }}"

# Disable yum from updating node.js since we are locking down this version for
# the application.
- name: disable nodejs from yum repo
  replace: >
    dest=/etc/yum.repos.d/nodesource-el.repo
    regexp='enabled=1'
    replace='enabled=0'
    backup=yes

- name: install exact npm version
  shell: npm i -g npm@{{ npm_version }}
