---
# Install specified version of node.js into the system

- name: add node.js rpm to yum
  shell: 'curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -'

- name: install nodejs
  yum:
    name: "nodejs-{{ nodejs_version }}"

- name: disable nodejs from yum repo
  replace: >
    dest=/etc/yum.repos.d/nodesource-el.repo
    regexp='enabled=1'
    replace='enabled=0'
    backup=yes

- name: install exact npm version
  shell: npm i -g npm@{{ npm_version }}
