---
# Simple script that runs "node --version" and look for the version
# of Nodejs that we are targeting (defined as a fact nodejs_version).
#
# Input vars:
#   nodejs_version
#
# Side effect:
#   nodejs_preinstalled set to true if the desired nodejs is already installed, false otherwise
#
- name : check if nodejs is installed
  shell: "node --version  | cut -c 2-"
  register: found_nodejs_version

- set_fact:
    nodejs_preinstalled: true
  when: found_nodejs_version.stdout == nodejs_version

- set_fact:
    nodejs_preinstalled: false
  when: found_nodejs_version.stdout != nodejs_version

- debug: msg="Found nodejs version {{nodejs_version}} - {{nodejs_preinstalled}}"
