# Reads the nvmrc file to determine the preferred nodejs
# version by the application.
#
# Side effect:
#   nodejs_version set to the version string used by the application.
#
- name: read node version
  shell: cat {{app_src}}/.nvmrc
  ignore_errors: yes
  register: nodejs_version_output

- set_fact:
    nodejs_version: "{{ nodejs_version_output.stdout }}"
  when: nodejs_version_output.stderr == ""
