- name: create launch configuration
  ec2_lc:
    region: "{{ region }}"
    name: "{{ launch_config_name }}"
    image_id: "{{ image_id }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    instance_monitoring: yes
    instance_profile_name: "{{ instance_profile_name }}"
    volumes: "{{ volumes | default(None) or omit }}"

- name: Configure Auto Scaling Group and perform rolling deploy
  ec2_asg:
    desired_capacity: "{{ desired_capacity | default(2) }}"
    health_check_period: 300
    health_check_type: ELB
    launch_config_name: "{{ launch_config_name }}"
    load_balancers: "{{ app_loadbalancers | default(None) or omit }}"
    max_size: "{{ max_size | default(2) }}"
    min_size: "{{ min_size | default(2) }}"
    name: "{{ auto_scaling_group_name }}"
    region: "{{ region }}"
    replace_all_instances: yes
    replace_batch_size: "{{ replace_batch_size | default(1) }}"
    state: present
    tags: "{{ app_tags | default(None) or omit }}"
    vpc_zone_identifier: "{{ app_subnets | default(None) or omit }}"
    wait_timeout: "{{ wait_timeout | default(480) }}"
  register: asg_result
