---
- name: upgrade all packages
  yum: name=* state=latest
  when: skip_update is undefined

- name: install RHEL's Extra Package Repository (epel)
  yum: name=epel-release state=latest
  when: skip_update is undefined

- name: install git
  yum: name=git state=present

- name: set timezone
  file: src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime owner=root group=root state=link force=true

- name: install Network Time Protocol (NTP) daemon
  yum: name=ntp state=latest

- name: start NTP service
  service: name=ntpd state=started enabled=true

- name: install selinux bindings
  yum: name=libselinux-python state=present

- name: install yum-cron
  yum: name=yum-cron state=latest

- name: configure yum-cron for security updates
  lineinfile: dest=/etc/yum/yum-cron.conf regexp=update_cmd line='update_cmd = security'
  when: skip_update is undefined

- name: configure yum-cron to automatically apply updates.
  lineinfile: dest=/etc/yum/yum-cron.conf regexp=apply_updates line='apply_updates = yes'
  when: skip_update is undefined

- name: set ulimit
  copy: src=files/limits.conf dest=/etc/security/limits.conf owner=root group=root force=true

- name: echo
  debug: msg="{{ name }} base OS is ready to go!"
