- name: echo
  debug: msg="launching '{{ instance_name }}' to {{ region }} from base image {{ ami_id }}"

- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet_id }}"
    group_id: "{{ security_groups }}"
    image: "{{ ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags: "{{ instance_tags|combine(default_tags) }}"
    instance_profile_name: "{{ instance_role|default('') }}"
    wait: yes
    assign_public_ip: yes
    count: 1
    user_data: "{{ user_data | default(None) or omit }}"
  register: ec2_result

- name: register a single ec2 instance result (guaranteed to be 1)
  set_fact:
    launched_instance: "{{ ec2_result.instances[0] }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ launched_instance.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started

- name: add new instance to {{playbook_group|default('specified group')}} so application playbook can be applied
  add_host: hostname={{ launched_instance.public_ip }} groups={{ playbook_group }} ansible_ssh_user={{ ami_user }} ec2_id={{ launched_instance.id }} ec2_name={{ launched_instance.tags['Name'] }}
  when: playbook_group is defined
