- name: echo
  debug: msg="launching '{{ instance_name }}' to {{ region }} from base image {{ ami_id }}"

- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    vpc_subnet_id: "{{ subnet_id }}"
    group_id: "{{ security_groups }}"
    image: "{{ ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags: "{{ instance_tags|combine(default_tags) }}"
    instance_profile_name: "{{ instance_role|default('') }}"
    wait: yes
    assign_public_ip: yes
  register: ec2

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: "{{ ec2.instances }}"

- name: add new instance to {{playbook_group|default('specified group')}} so application playbook can be applied
  add_host: hostname={{ item.public_ip }} groups={{ playbook_group }} ansible_ssh_user={{ ami_user }} ec2_id={{ item.id }} ec2_name={{ item.tags['Name'] }}
  with_items: "{{ ec2.instances }}"
  when: playbook_group is defined
