- name: add {{ user }} user
  user: name={{ user }} state=present

- name: make {{ user }} sudo
  template: src=sudoers dest=/etc/sudoers.d/{{ user }} owner=root group=root mode=0440 validate='visudo -cf %s'
  when: sudoer

- name: add a single authorized ssh key (optional)
  authorized_key: user={{ user }} key={{ public_key }} exclusive=True
  when: public_key is defined

- name: add multiple authorized ssh keys via list public keys (optional)
  copy:
    content: "{{ public_keys | join('\n') }}"
    dest: /home/{{ user }}/.ssh/authorized_keys
  when: public_keys is defined
