- name: Create AMI
  ec2_ami:
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
    name: "{{ item.tags['Name'] }}"
    wait: yes
    state: present
  with_items: "{{ ec2_instances }}"
  register: ami

- name: terminate instance
  ec2:
    state: absent
    instance_ids:
      - "{{ item.id }}"
    region: "{{ item.region }}"

  # can't use the jinja map(attribute=) filter, requires new jinja
  with_items: "{{ ec2_instances }}"

# TODO: create ASG from ami_id
