- name: Create AMI
  ec2_ami:
    region: "{{ ec2_instance.region }}"
    instance_id: "{{ ec2_instance.id }}"
    name: "{{ ec2_instance.tags['Name'] }}"
    wait: yes
    state: present
  register: ami

- name: echo
  debug: msg="{{ ami.image_id }} registered"

- name: terminate instance
  ec2:
    state: absent
    instance_ids:
      - "{{ ec2_instance.id }}"
    region: "{{ ec2_instance.region }}"
